# utils/__init__.py - Módulo de utilitários

from .constants import (
    SHEET_NAMES, SHEET_NAMES_EMOJI, STATUS_SYMBOLS, QUALITY_INDICATORS,
    MSG_CRAWLER_START, MSG_ANALYSIS_START, MSG_ANALYSIS_COMPLETE,
    MSG_CORRECTIONS_IMPLEMENTED, MSG_IMPROVEMENTS, MSG_NEW_CONSOLIDATED_TAB,
    STATUS_OK, STATUS_ABSENT, STATUS_TOO_SHORT, STATUS_TOO_LONG,
    GRAVITY_CRITICAL, GRAVITY_MEDIUM, GRAVITY_LOW,
    PROBLEM_TYPE_EMPTY, PROBLEM_TYPE_HIDDEN
)

__all__ = [
    'SHEET_NAMES',
    'SHEET_NAMES_EMOJI', 
    'STATUS_SYMBOLS',
    'QUALITY_INDICATORS',
    'MSG_CRAWLER_START',
    'MSG_ANALYSIS_START', 
    'MSG_ANALYSIS_COMPLETE',
    'MSG_CORRECTIONS_IMPLEMENTED',
    'MSG_IMPROVEMENTS',
    'MSG_NEW_CONSOLIDATED_TAB',
    'STATUS_OK',
    'STATUS_ABSENT',
    'STATUS_TOO_SHORT',
    'STATUS_TOO_LONG',
    'GRAVITY_CRITICAL',
    'GRAVITY_MEDIUM',
    'GRAVITY_LOW',
    'PROBLEM_TYPE_EMPTY',
    'PROBLEM_TYPE_HIDDEN'
]